name: to_do_list
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: 2.3.0
  flutterando_analysis: ^0.0.2
  flutter_launcher_icons: ^0.13.1
  intl: 0.18.0
  flutter_modular: ^6.3.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash/

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/splash/splash.jpg"
  android_12:
    image: "assets/splash/splash.jpg"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/app_icon/icon.png"
  min_sdk_android: 21