name: bank_project
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^6.3.2
  parse_server_sdk_flutter: ^7.0.0
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Greycliff
      fonts:
        - asset: assets/fonts/Greycliff_Bold.otf
          weight: 700
        - asset: assets/fonts/Greycliff_Regular.otf
          weight: 400
    - family: Barracuda
      fonts:
        - asset: assets/fonts/Barracuda_Bold.ttf
          weight: 700
        - asset: assets/fonts/Barracuda_Light.ttf
          weight: 300
        - asset: assets/fonts/Barracuda_Regular.ttf
          weight: 400
